mapper: minimap2 
mapper-options: -t 4
variant: gatk
variant-options: --sample_ploidy 2 --genotype_likelihoods_model SNP -rf BadCigar -out_mode EMIT_ALL_SITES -nt 4
filters:
  ad_ratio: 0.9
  min_depth: 10
  qual_score: 30
  mq_score: 30
annotators:
  - coverage
